homecoming/config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  mount Ckeditor::Engine => '/ckeditor'
  root 'static_pages#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'static_pages/home'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'profile', to: 'user#show'

  resources :destinations do
    resources :reviews do
      resources :comments, only: [:create, :destroy, :update]
    end
  end
  resources :users
  resources :groups, only: [:new, :create, :show, :destroy] do
    resources :news
  end
  get '/search' => 'destinations#search', :as => 'search_page'
  get '/create_group' => 'tests#create_group'
  get '/show_group' => 'tests#show_group'
  get '/destroy_group' => 'tests#destroy_group'
  get '/add_member_to_group' => 'tests#add_member_to_group'

  mount ActionCable.server => '/cable'
end

homecoming/app/models/destination.rb
class Destination < ApplicationRecord
    has_many :reviews, dependent: :destroy
    has_many :destination_category, dependent: :destroy
    has_many :category, through: :destination_category
    has_many :groups, inverse_of: :destination, dependent: :destroy

    validates :name, presence: true
    validates :address, presence: true
    mount_uploader :image, ImageUploader
    after_save :update_path

    def self.filter(rate,category,search)
        if(!search.blank?)
            all.where("lower(name) LIKE :search or lower(address) LIKE :search", search: "%#{@search}%").joins(:destination_category).where('category_id in (?)',category).joins(:reviews).having('round(avg(rating)) in (?)', rate).group(:id).order('destinations.created_at DESC')
        else
            joins(:destination_category).where('category_id in (?)',category).joins(:reviews).having('round(avg(rating)) in (?)', rate).group(:id).order('destinations.created_at DESC')
        end

    end

    private
        def update_path
            if (!self.image.blank?)
                self.update_column('picture_path',self.image.url)
            end
        end
end

homecoming/app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  def index
    if !params[:rates].blank? && !params[:categories].blank?
      @destinations = Destination.filter(params[:rates],params[:categories],params[:search])
      @destinations = @destinations.paginate(:page => params[:page], :per_page => 9)
    elsif params[:rates].blank? && params[:categories].blank? && params[:search].blank?
      @destinations = Destination.all
      @destinations = @destinations.paginate(:page => params[:page], :per_page => 9)
    else
      @destinations = []
    end
     
  end

  def show
    @destination = Destination.find(params[:id])
  end

  def new
    @destination = Destination.new
  end

  def edit
    @destination = Destination.find(params[:id])
  end

  def create
    @destination = Destination.new(destination_params)
    @destination.state = 1
    if @destination.save
      flash[:message] = "Request to create new destination: \"#{@destination.name}\" successfully"
      flash[:flash] = "success"
      redirect_to :action => 'index'
    else
      render :action =>'new'
    end
  end

  def update
    @destination = Destination.find(params[:id])
    if @destination.update_attributes(destination_param)
      redirect_to :action => "show", :id => @destination
    else
      render :action => 'edit'
    end
  end

  def destroy
    Destination.find(params[:id]).destroy
    redirect_to :action => 'index'
  end
  def top_page
    @top_destination = top_destination()
    @newest_destination = newest_destination()
    @best_destination = best_destination()
  end

  def search
  	if params[:search].blank? 
      redirect_to(destinations_path, alert: "Emptyfffffffffffffffff field!") and return  
    else  
      @parameter = params[:search].downcase  
      @destinations = Destination.all.where("lower(name) LIKE :search or lower(address) LIKE :search", search: "%#{@parameter}%").paginate(:page => params[:page], :per_page => 9) 
      render 'destinations/index'
    end  
  end

  private
  def destination_params
    params.require(
      :destination
    ).permit(
      :name,
      :image,
      :address,
      :speciality
    )

  end
end

homecoming/app/helpers/destinations_helper.rb
module DestinationsHelper
    def google_map(center)
        center.gsub! ' ', '+'
        "https://www.google.com/maps/embed/v1/place?q=#{center}&key=AIzaSyDawjr56ZnzpNjJ3sfRqQQiJtyE1JNc6AA"
    end

    def ave_rating(sum, count)
        if count == 0
            0
        else
            sum/count
        end
    end

    def get_destinations
        Destination.all.collect do |destination|
            [destination.name, destination.id]
        end
    end
end

homecoming/app/views/destinations/edit.html.erb
<h1>Destinations#edit</h1>
<p>Find me in app/views/destinations/edit.html.erb</p>

homecoming/app/views/destinations/index.html.erb
<!-- Main content area -->
<main class="container">
    <div class="row">

        <!-- Sidebar -->
        <aside class="col-md-4">
            <div class="sidebar-box">
                <h4>Filter</h4>
                <%= form_tag destinations_path, :method => 'get', :id => "destinations_filter", remote: true, :dataType => "script" do %>
                <div class="list-group list-group-root">
                    <a class="list-group-item" href="index.html">Home Page</a>
                    <%= hidden_field_tag('search',value= params[:search])%>
                    <a class="list-group-item">Filter by rating</a>
                    <div class="list-group"> 
                        <% (0..5).step(1) do |i|%>
                        <a class="list-group-item img-check active"> <strong> <%= render 'shared/star', :locals => {:rating => i  }%></strong>
                        <%= check_box_tag("rates[]", i, checked = true, class: 'hidden checkbox') %>
                        </a>
                        <%end%>
                    </div>
                    <a class="list-group-item">Filter by location</a>
                    <div class="list-group"> 
                        <% Category.all.each do |category|%>
                        <a class="list-group-item img-check active">  <%= category['name']%>
                        <%= check_box_tag("categories[]", category['id'], checked = true, class: 'hidden checkbox') %>
                        </a>
                        <% end %>
                    </div>
                </div>
                <%end%>
            </div>

            <div class="sidebar-box sidebar-box-bg">
                <h4>About us</h4>
                <p>Aenean nec massa a tortor auctor sodales sed a dolor. Duis vitae lorem sem. Proin at velit vel arcu
                    pretium luctus. <a href="#" class="readmore">Read More &raquo;</a></p>
            </div>
            <div class="sidebar-box">
                <h4>Helpful Links</h4>
                <ul>
                    <li><a href="http://www.themeforest.net/?ref=spykawg" title="premium templates">Premium HTML web
                            templates from $10</a></li>
                    <li><a href="http://www.dreamhost.com/r.cgi?259541" title="web hosting">Cheap web hosting from
                            Dreamhost</a></li>
                    <li><a href="http://tuxthemes.com" title="Tux Themes">Premium WordPress themes</a></li>
                </ul>
            </div>
        </aside>

        <!-- Main content -->
        <div class="col-md-8">
        <div class="well well-sm" id="filterrific_results">
        <%if params[:search].blank? %>
        <strong> List Destination</strong>
        <%else%>
        <strong> <%= params[:search]%></strong>
        <%end%>
    </div>


            <div id = "destinations">
                <%= render 'shared/list_destination', :destinations => @destinations%>
            </div>
        </div>



        <!-- Bootcamp JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
</main>
<style>

</style>
<script>

$(document).ready(function(e){
    $(".img-check").click(function(){
        var checkbox = $(this).find(".checkbox")[0];
        var check = checkbox.checked
        if (check == false){
            $(this).toggleClass("active");
            $(checkbox).prop('checked',true);      
            $.ajax({
                url: '/destinations',
                type: "GET",
                dataType: "script",
                data:  $("#destinations_filter").serialize()
            })     
        }
        else{
            console.log(checkbox.checked); 
            $(this).removeClass("active");
            $(checkbox).prop('checked',false);
            $.ajax({
                url: $("#destinations_filter").attr("action"),
                type: "GET",
                dataType: "script",
                data:  $("#destinations_filter").serialize()
            })   

        }
	});
});


</script>
<script src="../assets/star.js"></script>

homecoming/app/views/destinations/index.js.erb
$("#destinations").html("<%= j render('shared/list_destination', :destinations => @destinations) %>");

homecoming/app/views/destinations/new.html.erb
<%= csrf_meta_tags %>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<!------ Include the above in your HEAD tag ---------->
<div class="container">
	<div class="col-md-9">
		<div class="card">
			<div class="card-body">
				<div class="row">
					<div class="col-md-12">
						<h4 class="heading"><strong>Destination </strong> Add <span></span></h4>
						<hr>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
					<%= form_for @destination do |f| %>	
						<div class="form-group row">
							<%= f.label :name,  "Destination Name *", class: "col-4 col-form-label" %>
							<div class="col-8">
							<%= f.text_field :name, class: "form-control here", required: true, placeholder: "Destination name" %>
							</div>
						</div>
						<div class="form-group row">
						<%= f.label :address, "Address *", class: "col-4 col-form-label" %>
						<div class="col-8">
						<%= f.text_field :address, class: "form-control here", required: true, placeholder: "Address" %><br />
						</div>
						</div>

						<div class="form-group row">
						<%= f.label :speciality, "Speciality *", class: "col-4 col-form-label" %>
						<div class="col-8">
						<%= f.text_field :speciality, class: "form-control here", required: true, placeholder: "Describe it" %><br />
						</div>
						</div>

						<div class="form-group row">
						<%= f.label :image, "Picture *", class: "col-4 col-form-label" %>
						<div class="col-8">
							<img src="#" class="avatar img-circle img-thumbnail" alt="avatar" style="display :none;width :700px">
							<h6>Upload a different photo...</h6>
							<%= f.file_field :image, class: "text-center center-block file-upload", id: "picture_path", required: true %>
						</div>
					</div>
					<div class="form-group row">
					<div class="offset-4 col-8">
						<%= f.submit "Add new Destination", class: "btn btn-primary" %>
					</div>
				</div>

						
					  
						
					  <% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</div>

</div>
<style>
	body {
		background: #F1F3FA;
	}

	.heading {
		border-bottom: 1px solid #A9A59F;
		padding-bottom: 9px;
		position: relative;
	}

	.heading span {
		background: #6D6C6A none repeat scroll 0 0;
		bottom: -2px;
		height: 3px;
		left: 0;
		position: absolute;
		width: 75px;
	}
</style>
<script src="../assets/image_upload.js"></script>

homecoming/app/views/destinations/show.html.erb
<!------ Include the above in your HEAD tag ---------->
<main>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <div class="container">
        <!-- Portfolio Item Row -->
        <% if flash[:message] %>
        <div class="alert alert-<%= flash[:flash] %>" role="alert">
            <%= flash[:message] %>
        </div>
        <% end %>

        <div class="row">
            <div class="col-md-8">
                <img class="img-responsive" src="<%= @destination.picture_path%>" alt="">
            </div>

            <div class="col-md-4">
                <div class="card">
                    <div class="card-content">
                        <span class="card-title">
                            <h3>
                                <%= @destination.name%>
                            </h3>
                        </span>
                        <div>
                            <iframe style="margin-left: 4px;height: 315px;width: 491px;" frameborder="0" style="border:0"
                                src="<%=google_map(@destination.name)%>" allowfullscreen>
                            </iframe>
                        </div>
                        <ul>
                            <li> Address: <strong>
                                    <%= @destination.address%></strong> </li>
                            <li> Speciality: <strong>
                                    <%= @destination.speciality%></strong> </li>
                            <li> Reviewed by: <strong>
                                    <%= @destination.reviews.count%> </strong></li>
                            <li>
                                <%= render 'shared/star', :locals => {:rating => ave_rating(@destination.reviews.sum(:rating),@destination.reviews.count)  }%>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div>
                <h3 class="page-header">Reviews</h3>
            </div>
            <% if @destination.reviews.count != 0 %>
            <% @destination.reviews.each do |review| %>
            <div class="row">
                <div class="well" style="background-color:#ffffff">
                    <div class="media" style="height: 170px">
                        <div class="pull-left">
                            <% if review.user.picture_path != nil %>
                                <img class="media-object" style ="width: auto; height: 150px" src= " <%=review.user.picture_path%>" alt = "have image">
                            <% else %>
                                <img class="media-object" style ="width: auto; height: 150px" src="https://us.123rf.com/450wm/apoev/apoev1709/apoev170900088/85467744-default-avatar-anime-girl-profile-icon-grey-photo-manga-placeholder.jpg?ver=6" >
                            <% end %>
                            <p style="width: 150px;text-align:center">
                                <%= link_to review.user.nickname, controller: "users", action: "show", id: review.user.id %>
                            </p>
                        </div>

                        <div class="media-body" style="width:900px">
                            <h3 class="media-heading">
                                <%= link_to review.title, [@destination, review] %>
                            </h3>

                            <div style="height:60px;line-height:20px; /* Height / no. of lines to display */overflow:hidden; margin-bottom:30px">
                                <%= review.content.html_safe %>
                            </div>

                            <ul class="list-inline list-unstyled text-right">
                                <li><span><i class="glyphicon glyphicon-calendar"></i>
                                        <%= review.created_at%> </span></li>
                                <li>|</li>
                                <span><i class="glyphicon glyphicon-comment"></i>
                                    <%= review.comments.count%></span>
                                <li>|</li>
                                <li>
                                    <%= render 'shared/star', :locals => {:rating => review.rating  }%>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <%end%>
            <% else %>
                <div class="offset-4 col-8">
                    <p><strong> There is no review. </strong></p>
                </div>
            <% end %>
            <hr>
            <% if user_signed_in?%>
                <div class="offset-4 col-8">
                    <%= link_to "Create new review", new_destination_review_path(@destination), :class => 'btn btn-primary' %>
                </div>
            <% end %>
        </div>
    </div>
</main>
<script src="../assets/star.js"></script>