homecoming/config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  mount Ckeditor::Engine => '/ckeditor'
  root 'static_pages#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'static_pages/home'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'profile', to: 'user#show'

  resources :destinations do
    resources :reviews do
      resources :comments, only: [:create, :destroy, :update]
    end
  end
  resources :users
  resources :groups, only: [:new, :create, :show, :destroy] do
    resources :news
  end
  get '/search' => 'destinations#search', :as => 'search_page'
  get '/create_group' => 'tests#create_group'
  get '/show_group' => 'tests#show_group'
  get '/destroy_group' => 'tests#destroy_group'
  get '/add_member_to_group' => 'tests#add_member_to_group'

  mount ActionCable.server => '/cable'
end

homecoming/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base  
  self.abstract_class = true
end

homecoming/app/models/category.rb
class Category < ApplicationRecord
    has_many :destination_categories, dependent: :destroy
    has_many :destination, through: :destination_category
end

homecoming/app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :review
    has_many :children, class_name: 'Comment', foreign_key: 'parent_id', dependent: :destroy, inverse_of: 'parent'
    belongs_to :parent, class_name: 'Comment', optional: true

    validates :content, presence: true
    validates :user, presence: true
    validates :review, presence: true

    acts_as_tree order: "created_at ASC"

    after_create_commit { notify }

    private
    def notify
        review = Review.find_by(id: self.review_id)
        destination = Destination.find_by(id: review.destination_id)
        Notification.create(event: "New comment review on post (#{destination.name})", comment_id: self.id, review_id: self.review_id, destination_id: review.destination_id)
    end
end

homecoming/app/models/destination.rb
class Destination < ApplicationRecord
    has_many :reviews, dependent: :destroy
    has_many :destination_category, dependent: :destroy
    has_many :category, through: :destination_category
    has_many :groups, inverse_of: :destination, dependent: :destroy

    validates :name, presence: true
    validates :address, presence: true
    mount_uploader :image, ImageUploader
    after_save :update_path

    def self.filter(rate,category,search)
        if(!search.blank?)
            all.where("lower(name) LIKE :search or lower(address) LIKE :search", search: "%#{@search}%").joins(:destination_category).where('category_id in (?)',category).joins(:reviews).having('round(avg(rating)) in (?)', rate).group(:id).order('destinations.created_at DESC')
        else
            joins(:destination_category).where('category_id in (?)',category).joins(:reviews).having('round(avg(rating)) in (?)', rate).group(:id).order('destinations.created_at DESC')
        end

    end

    private
        def update_path
            if (!self.image.blank?)
                self.update_column('picture_path',self.image.url)
            end
        end
end

homecoming/app/models/group.rb
class Group < ApplicationRecord
    belongs_to :owner, class_name: :User, foreign_key: :owner_id
    has_and_belongs_to_many :members, class_name: :User, foreign_key: :group_id, association_foreign_key: :user_id
    belongs_to :destination
    has_many :messages, dependent: :destroy
    has_many :news
end

homecoming/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

homecoming/app/models/news.rb
class News < ApplicationRecord
    belongs_to :user
    belongs_to :group
end

homecoming/app/models/notification.rb
class Notification < ApplicationRecord
  after_create_commit { NotificationBroadcastJob.perform_later(Notification.where('created_at >= :one_hours_ago', :one_hours_ago  => Time.now - 1.hours).reverse.count,self)}
end

homecoming/app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :destination
    has_many :comments, dependent: :destroy

    validates :title, presence: true
    validates :rating, presence: true
    validates :content, presence: true
    validates :user, presence: true
    validates :destination, presence: true
end

homecoming/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :reviews, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :groups, inverse_of: :owner, dependent: :destroy, class_name: :Group, foreign_key: :owner_id
    has_and_belongs_to_many :joining_groups, class_name: :Group, foreign_key: :user_id, association_foreign_key: :group_id
    has_many :messages, dependent: :destroy

    validates :email, presence: true, uniqueness: true
    # validates :nickname, presence: true
    # validates :password, presence: true
end

homecoming/app/controllers/news_controller.rb
class NewsController < ApplicationController

    def index
        @group = Group.find(params[:group_id])
        redirect_to group_path(@group)
    end

    def show
        @news = News.find(params[:id])
    end

    def new
        group_id = params[:group_id]
        @group = Group.find(group_id)
        @news = @group.news.build
        @user = User.find(1)
        @news.user = @user
    end

    def edit
        @news = News.find(params[:id])
    end

    def create
        @group = Group.find(params[:group_id])
        @news = @group.news.build(news_params)
        @user = User.find(params[:news][:user_id])
        @news.user = @user
        if @news.save
            flash[:message] = "Create new news \"#{@news.title}\" successfully"
            flash[:flash] = "success"
            redirect_to group_path(@group)
        else
            render :action =>'new'
        end
    end

    def update
        @news = News.find(params[:id])
        if @news.update(news_params)
            redirect_to group_path(@news.group)
        else
            render :action =>'edit'
        end
    end

    def destroy
        @news = News.find(params[:id])
        if @news.destroy
            flash[:message] = "Delete news \"#{@news.title}\" successfully"
            flash[:flash] = "success"
        else
            flash[:message] = "Can not delete news \"#{@news.title}\" successfully"
            flash[:flash] = "danger"
        end
        
        redirect_to group_path(@news.group)
    end

    private
    def news_params
        params.require(
          :news
        ).permit(
          :title,
          :content,
          :user_id
        )
    end
end

homecoming/app/helpers/application_helper.rb
module ApplicationHelper
end

homecoming/app/helpers/comments_helper.rb
module CommentsHelper
  def comments_tree_for comments, post
      safe_join(comments.map do |comment, nested_comments|
                  print(comment)
                  print(nested_comments)
                  render(comment, review: post, comment_new: Comment.new) + tree(comment, nested_comments, post)
                end
      )
  end
  def tree comment, nested_comments, post
    if nested_comments.empty?
      render :partial => 'comments/replies_for', :locals => {:comment_id => comment.id }
    else
      content_tag :div, comments_tree_for(nested_comments, post), class: "replies", id: ("replies-for-" + comment.id.to_s)
    end
  end
end

homecoming/app/helpers/groups_helper.rb
module GroupsHelper
end

homecoming/app/helpers/news_helper.rb
module NewsHelper
end

homecoming/app/helpers/reviews_helper.rb
module ReviewsHelper
end

homecoming/app/helpers/search_helper.rb
module SearchHelper
end

homecoming/app/helpers/sessions_helper.rb
module SessionsHelper
	def get_members
        User.all
    end
end

homecoming/app/helpers/tests_helper.rb
module TestsHelper
end

homecoming/app/helpers/users_helper.rb
module UsersHelper
    def get_members
        User.all
    end
end

homecoming/app/views/layouts/_rails_default.html.erb
  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
        <link rel="stylesheet" href="/assets/pagelist.css">
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

homecoming/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homecoming</title>
      <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
        <link rel="stylesheet" href="/assets/pagelist.css">
        <link rel="stylesheet" type="text/css" href="/assets/review.css">
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link href="/assets/editor.css" type="text/css" rel="stylesheet"/>
    <%= render 'layouts/rails_default' %>
  </head>

  <body >
    <%= render 'shared/header' %>
    <!-- <p class="notice"><%= notice %></p> -->
    <!-- <p class="alert"><%= alert %></p> -->
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
    <script src="/assets/editor.js"></script>
    
    <script>
      $(document).ready(function() {
        $("#txtEditor").Editor();
      });
    </script>
</html>
  

homecoming/app/views/pagelist/text.html.erb
        <!-- Main content area -->
        <main class="container">
            <div class="row">
                             
                <!-- Sidebar -->
                <aside class="col-md-4">
                    <div class="sidebar-box">
                        <h4>Categories</h4>
                        <div class="list-group list-group-root">
                            <a class="list-group-item" href="index.html">Home Page</a>
                            <a class="list-group-item" href="examples.html">Place</a>
                            <div class="list-group">
                                <a class="list-group-item" href="three-column.html">new Place </a>
                                <a class="list-group-item" href="one-column.html">Place hot</a>
                                <a class="list-group-item active" href="text.html">Place suitable</a>	
                            </div>
                            <a class="list-group-item" href="three-column.html">Place suggestions</a>
                        </div>
                    </div>

                    <div class="sidebar-box sidebar-box-bg">
                        <h4>About us</h4>
                        <p>Aenean nec massa a tortor auctor sodales sed a dolor. Duis vitae lorem sem. Proin at velit vel arcu pretium luctus. <a href="#" class="readmore">Read More &raquo;</a></p>    
                    </div>

                    <div class="sidebar-box">
                        <h4>Search site</h4>
                        <form class="form-inline my-2 my-lg-0">
                            <input class="form-control mr-sm-2" type="text"  placeholder="Search" aria-label="Search">
                            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                        </form>
                    </div>

                    <div class="sidebar-box">
                        <h4>Helpful Links</h4>
                        <ul>
                            <li><a href="http://www.themeforest.net/?ref=spykawg" title="premium templates">Premium HTML web templates from $10</a></li>
                            <li><a href="http://www.dreamhost.com/r.cgi?259541" title="web hosting">Cheap web hosting from Dreamhost</a></li>
                            <li><a href="http://tuxthemes.com" title="Tux Themes">Premium WordPress themes</a></li>
                        </ul>
                    </div>
                </aside> 
                
                <!-- Main content -->
                <div class="col-md-8">
                    
                    <div class="container">
    <div class="well well-sm">
        <strong>Category Title</strong>
        <div class="btn-group">
            <a href="#" id="list" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-th-list">
            </span>List</a> <a href="#" id="grid" class="btn btn-default btn-sm"><span
                class="glyphicon glyphicon-th"></span>Grid</a>
        </div>
    </div>
    <div id="products" class="row list-group">
        <div class="item ">
            <div class="thumbnail">
                <img class="group list-group-image" src="https://advertisingvietnam.com/wp-content/uploads/2018/04/Du-l%E1%BB%8Bch-Vi%E1%BB%87t-Nam.jpg" alt="" />
                <div class="caption">
                    <h4 class="group inner list-group-item-heading">
                        nha trang</h4>
                    <p class="group inner list-group-item-text">
                        Product description... Lorem ipsum dolor sit amet, consectetuer adipiscing elit,
                        sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>
                    <div class="row">
                        <div class="col-xs-12 col-md-6">
                            <p class="lead">
                                </p>
                        </div>
                        <div class="col-xs-12 col-md-6">
                            <a class="btn btn-success" href="http://www.jquery2dotnet.com">See More</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="item  ">
            <div class="thumbnail">
                <img class="group list-group-image" src="https://advertisingvietnam.com/wp-content/uploads/2018/04/Du-l%E1%BB%8Bch-Vi%E1%BB%87t-Nam.jpg" alt="" />
                <div class="caption">
                    <h4 class="group inner list-group-item-heading">
                        phu quoc</h4>
                    <p class="group inner list-group-item-text">
                        Product description... Lorem ipsum dolor sit amet, consectetuer adipiscing elit,
                        sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>
                    <div class="row">
                        <div class="col-xs-12 col-md-6">
                            <p class="lead">
                                </p>
                        </div>
                        <div class="col-xs-12 col-md-6">
                            <a class="btn btn-success" href="http://www.jquery2dotnet.com">See More</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="item  ">
            <div class="thumbnail">
                <img class="group list-group-image" src="https://advertisingvietnam.com/wp-content/uploads/2018/04/Du-l%E1%BB%8Bch-Vi%E1%BB%87t-Nam.jpg" alt="rss feed" />
                <div class="caption">
                    <h4 class="group inner list-group-item-heading">
                        hai thinh</h4>
                    <p class="group inner list-group-item-text">
                        Product description... Lorem ipsum dolor sit amet, consectetuer adipiscing elit,
                        sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>
                    <div class="row">
                        <div class="col-xs-12 col-md-6">
                            <p class="lead">
                                </p>
                        </div>
                        <div class="col-xs-12 col-md-6">
                            <a class="btn btn-success" href="http://www.jquery2dotnet.com">See More</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="item ">
            <div class="thumbnail">
                <img class="group list-group-image" src="https://advertisingvietnam.com/wp-content/uploads/2018/04/Du-l%E1%BB%8Bch-Vi%E1%BB%87t-Nam.jpg" alt="" />
                <div class="caption">
                    <h4 class="group inner list-group-item-heading">
                        sam son</h4>
                    <p class="group inner list-group-item-text">
                        Product description... Lorem ipsum dolor sit amet, consectetuer adipiscing elit,
                        sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>
                    <div class="row">
                        <div class="col-xs-12 col-md-6">
                            <p class="lead">
                               </p>
                        </div>
                        <div class="col-xs-12 col-md-6">
                            <a class="btn btn-success" href="http://www.jquery2dotnet.com">See More</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

                    # list index
                </div>             
            </div> 



        <!-- Bootcamp JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
       <link rel="stylesheet" href="css/style.css">

        <!-- Font Awesome -->
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<script>
$(document).ready(function() {
    $('#list').click(function(event){event.preventDefault();$('#products .item').addClass('list-group-item');});
    $('#grid').click(function(event){event.preventDefault();$('#products .item').removeClass('list-group-item');$('#products .item').addClass('grid-group-item');});
});
</script>
<style>
.glyphicon { margin-right:5px; }
.thumbnail
{
    margin-bottom: 20px;
    padding: 0px;
    -webkit-border-radius: 0px;
    -moz-border-radius: 0px;
    border-radius: 0px;
}

.item.list-group-item
{
    float: none;
    width: 100%;
    background-color: #fff;
    margin-bottom: 10px;
}
.item.list-group-item:nth-of-type(odd):hover,.item.list-group-item:hover
{
    background: #428bca;
}

.item.list-group-item .list-group-image
{
    margin-right: 10px;
}
.item.list-group-item .thumbnail
{
    margin-bottom: 0px;
}
.item.list-group-item .caption
{
    padding: 9px 9px 0px 9px;
}
.item.list-group-item:nth-of-type(odd)
{
    background: #eeeeee;
}

.item.list-group-item:before, .item.list-group-item:after
{
    display: table;
    content: " ";
}

.item.list-group-item img
{
    float: left;
}
.item.list-group-item:after
{
    clear: both;
}
.list-group-item-text
{
    margin: 0 0 11px;
}

</style>
</main>

homecoming/app/views/shared/_footer.html.erb
<footer class="footer">
<div class="footer-lists">
    <div class="container">
        <div class="row">
            <div class="col-sm">
                <ul>
                    <li><h4>Proin accumsan</h4></li>
                    <li><a href="#">Rutrum nulla a ultrices</a></li>
                    <li><a href="#">Blandit elementum</a></li>
                    <li><a href="#">Proin placerat accumsan</a></li>
                    <li><a href="#">Morbi hendrerit libero </a></li>
                    <li><a href="#">Curabitur sit amet tellus</a></li>
                </ul>
            </div>
            <div class="col-sm">
                <ul>
                    <li><h4>Condimentum</h4></li>
                    <li><a href="#">Curabitur sit amet tellus</a></li>
                    <li><a href="#">Morbi hendrerit libero </a></li>
                    <li><a href="#">Proin placerat accumsan</a></li>
                    <li><a href="#">Rutrum nulla a ultrices</a></li>
                    <li><a href="#">Cras dictum</a></li>
                </ul>
            </div>   
            <div class="col-sm">
                <ul>
                    <li><h4>Suspendisse</h4></li>
                    <li><a href="#">Morbi hendrerit libero </a></li>
                    <li><a href="#">Proin placerat accumsan</a></li>
                    <li><a href="#">Rutrum nulla a ultrices</a></li>
                    <li><a href="#">Curabitur sit amet tellus</a></li>
                    <li><a href="#">Donec in ligula nisl.</a></li>
                </ul>
            </div>
            <div class="col-sm">
                <h4>Suspendisse</h4>
                <p>Integer mattis blandit turpis, quis rutrum est. Maecenas quis arcu vel felis lobortis iaculis fringilla at ligula. Nunc dignissim porttitor dolor eget porta.</p>

                <p class="social-icons">
                    <a href="#"><i class="fa fa-facebook fa-2x"></i></a>
                    <a href="#"><i class="fa fa-twitter fa-2x"></i></a>
                    <a href="#"><i class="fa fa-youtube fa-2x"></i></a>
                    <a href="#"><i class="fa fa-instagram fa-2x"></i></a>
                </p>
            </div>
        </div>
    </div>
</div>


<div class="footer-bottom">
        <p class="text-center">Create by Homecoming.. <a href="https://zypopwebtemplates.com/">ZyPop</a>.</p>
        <p class="text-center"><a href="#">Back to top</a></p>
</div>

</footer>

homecoming/app/views/shared/_header.html.erb
<header class="header-image" style="background-image: url('../assets/bg1.jpg');height:160px;">
<!-- Main navigation -->
<div class="row" style="margin-left: 580px;">
  <%= form_tag(search_page_path, :method => "get",
    class: 'navbar-form navbar-left') do %>
  <div class="input-group">
    <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>
    <div class="input-group-btn">
      <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>
    </div>
  </div>
<% end %>
</div>
<nav class="row navbar navbar-expand-md navbar-dark" style="margin-top: 10px;">
    <div class="container">

        <!-- Company name shown on mobile -->
        <a class="navbar-brand" href="/">HomeComming</a>

        <!-- Mobile menu toggle -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainNavbar" aria-controls="mainNavbar" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Main navigation items -->
        <div class="collapse navbar-collapse" id="mainNavbar">
            <ul class="navbar-nav mr-auto justify-content-end">
                <li class="nav-item active">
                        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                </li>
                <% if user_signed_in? %>
                <li class="nav-item dropdown">
                             <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="dropdownMenuLink" role="button" aria-haspopup="true" aria-expanded="false">Place</a>
                                        <div class="dropdown-menu navbar-dark bg-primary" aria-labelledby="dropdownMenuLink">
                                              <a class="nav-link" href="/destinations/new">New place</a>
                                              <a class="nav-link" href="/destinations">Place all</a>
                                        </div>
                </li>
                <%else%>
                <li class="nav-item">
                        <a class="nav-link" href="/destinations">Place all</a>
                </li>
                <%end%>

                <li class="nav-item">
                        <a class="nav-link" href="#">Contact</a>
                </li>
                <% if user_signed_in? %>
                    <% if current_user.admin == true %>
                    <li class="nav-item">
                        <%= link_to "Admin", rails_admin_path, class: "nav-link" %>
                    </li>
                    <% end %>
                    <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="profile" role="button" aria-haspopup="true" aria-expanded="false"><%=current_user.email.split('@')[0]%></a>
                               <div class="dropdown-menu navbar-dark bg-primary" aria-labelledby="profile">
                               <%= link_to "New group", '/groups/new', class: "nav-link" %>
                                    <%= link_to "Profile", current_user, class: "nav-link" %>
                                     <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
                               </div>
       </li>
                    <li class="nav-item">
                      <%= render "notifications/notification_center", notifications: @notifications %>
                    </li>
                <% else %>
                    <li class="nav-item">
                        <%= link_to "Login", user_session_path, class: "nav-link" %>
                    </li>
                <% end %>
            </ul>

        </div>



    </div>
</nav>



<!-- Jumbtron / Slider -->
<style type="text/css">
    .search-form .form-group {
  float: right !important;
  transition: all 0.35s, border-radius 0s;
  width: 32px;
  height: 32px;
  background-color: #fff;
  box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset;
  border-radius: 25px;
  border: 1px solid #ccc;
}
.search-form .form-group input.form-control {
  padding-right: 20px;
  border: 0 none;
  background: transparent;
  box-shadow: none;
  display:block;
}
.search-form .form-group input.form-control::-webkit-input-placeholder {
  display: none;
}
.search-form .form-group input.form-control:-moz-placeholder {
  /* Firefox 18- */
  display: none;
}
.search-form .form-group input.form-control::-moz-placeholder {
  /* Firefox 19+ */
  display: none;
}
.search-form .form-group input.form-control:-ms-input-placeholder {
  display: none;
}
.search-form .form-group:hover,
.search-form .form-group.hover {
  width: 100%;
  border-radius: 4px 25px 25px 4px;
}
.search-form .form-group span.form-control-feedback {
  position: absolute;
  top: -1px;
  right: -2px;
  z-index: 2;
  display: block;
  width: 34px;
  height: 34px;
  line-height: 34px;
  text-align: center;
  color: #3596e0;
  left: initial;
  font-size: 14px;
}
</style>

</header>

homecoming/app/views/shared/_list_destination.html.erb
<article>
<% if !destinations.blank? %>
            <div class="card-container" style="padding: 0rem 0 !important;">
            <div class="container">
                <div class="padded-box row">
                <% destinations.each do |destination|%>
                    <div class="col-md-4">
                        <div class="card text-center" style= "height: 297px;width: 230px;margin-bottom : 20px;">
                          <img class="card-img-top" style="width: 100%; height : 170px" src="<%= destination.picture_path %>" alt="Card image cap">
                          <div class="card-body">
                            <p class="card-text" style= "height: 31px;width: 200px;"><%= destination.speciality%></p>
                            <a href="/destinations/<%=destination.id%>" class="btn btn-primary" style='white-space: nowrap;overflow: hidden;text-overflow: ellipsis;width: 130px;' > <%= destination.name%></a>
                          </div>
                        </div>
                    </div>
                    <% end %>
                </div>
            </div>
        </div>
                <div><%= will_paginate @destinations, renderer: WillPaginate::ActionView::BootstrapLinkRenderer%> </div>
                <%else%>
                <div> There's no destination</div>
                <%end%>
        </article>

homecoming/app/views/shared/_search.html.erb
<div class="row">
    <div class="col-md-4 col-md-offset-3">
            <form action="" class="search-form">
                <div class="form-group has-feedback">
                    <label for="search" class="sr-only">Search</label>
                    <input type="text" class="form-control" name="search" id="search" placeholder="search">
                    <span class="glyphicon glyphicon-search form-control-feedback"></span>
                </div>
            </form>
        </div>
    </div>

homecoming/app/views/shared/_star.html.erb
<div class="star-rating" display="inline">
    <span class="fa fa-star-o" data-rating="1"></span>
    <span class="fa fa-star-o" data-rating="2"></span>
    <span class="fa fa-star-o" data-rating="3"></span>
    <span class="fa fa-star-o" data-rating="4"></span>
    <span class="fa fa-star-o" data-rating="5"></span>
    <input type="hidden" class="rating-value" value= <%= locals[:rating] %> >
    <strong class = "type">
    <%= locals[:rating] %></strong>
</div> 