homecoming/config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  mount Ckeditor::Engine => '/ckeditor'
  root 'static_pages#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'static_pages/home'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'profile', to: 'user#show'

  resources :destinations do
    resources :reviews do
      resources :comments, only: [:create, :destroy, :update]
    end
  end
  resources :users
  resources :groups, only: [:new, :create, :show, :destroy] do
    resources :news
  end
  get '/search' => 'destinations#search', :as => 'search_page'
  get '/create_group' => 'tests#create_group'
  get '/show_group' => 'tests#show_group'
  get '/destroy_group' => 'tests#destroy_group'
  get '/add_member_to_group' => 'tests#add_member_to_group'

  mount ActionCable.server => '/cable'
end

homecoming/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def index
        @destination = Destination.find(params[:destination_id])
        redirect_to destination_path(@destination)
    end

    def show
        @review = Review.find(params[:id])
        @comment = Comment.new
        @comments = @review.comments
    end

    def new
        destination_id = params[:destination_id]
        @destination = Destination.find(destination_id)
        @review = @destination.reviews.build
        @review.rating = 0
        @user = User.find(1)
        @review.user = @user
    end

    def edit
        @review = Review.find(params[:id])
    end

    def create
        @destination = Destination.find(params[:destination_id])
        @review = @destination.reviews.build(review_params)
        @user = User.find(params[:review][:user_id])
        @review.user = @user
        if @review.save
            flash[:message] = "Create new review \"#{@review.title}\" successfully"
            flash[:flash] = "success"
            redirect_to destination_path(@destination)
        else
            render :action =>'new'
        end
    end

    def update
        @review = Review.find(params[:id])
        if @review.update(review_params)
            redirect_to destination_path(@review.destination)
        else
            render :action =>'edit'
        end
    end

    def destroy
        @review = Review.find(params[:id])
        if @review.destroy
            flash[:message] = "Delete review \"#{@review.title}\" successfully"
            flash[:flash] = "success"
        else
            flash[:message] = "Can not delete review \"#{@review.title}\" successfully"
            flash[:flash] = "danger"
        end
        
        redirect_to destination_path(@review.destination)
    end

    private
    def review_params
        params.require(
          :review
        ).permit(
          :title,
          :rating,
          :content
        )
    end
end

homecoming/app/helpers/reviews_helper.rb
module ReviewsHelper
end

homecoming/app/views/reviews/edit.html.erb
<div class="container">
<% if @review.errors.any? %>
    <div class="alert alert-danger" role="alert">
        <%= @review.errors.full_messages.first %>
    </div>
<% end %>
<hr>
<h2>Create new review for destination: 
    <span class="badge badge-secondary">
        <%= @review.destination.name %>
    </span>
</h2>

<%= form_for [@review.destination, @review] do |f| %>
  <div>
    <%= f.label :title %>
  </div>
  <div>
    <%= f.text_field :title, :class => 'col-12' %>
  </div>
  <hr>
  <div>
  <%= f.label :rating %>
</div>
  <div class="star-rating" display="inline">
    <span class="fa fa-star-o" data-rating="1"></span>
    <span class="fa fa-star-o" data-rating="2"></span>
    <span class="fa fa-star-o" data-rating="3"></span>
    <span class="fa fa-star-o" data-rating="4"></span>
    <span class="fa fa-star-o" data-rating="5"></span>
    <%= f.text_field :rating, :type => "hidden", :class => "rating-value" %>
    <strong class = "type">address</strong>
</div> 
  <hr>
  <div>
    <%= f.label :content %>
  </div>
  <div>
    <%= f.cktext_area :content, rows: 10 %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

<hr>
<div class="item ">
    <div class="thumbnail">
        <div class="caption">
            <h4 class="group inner list-group-item-heading">
                <span class="badge badge-secondary">Destination: </span>
                <%= @review.destination.name %></h4>
        <p class="group inner list-group-item-text">
            <span class="badge badge-secondary">Address: </span>
            <%= @review.destination.address %></h4></p>
        <p class="group inner list-group-item-text">
            <span class="badge badge-secondary">Speciality: </span>
            <%= @review.destination.speciality %></h4></p>
            <img class="group list-group-image" src="https://advertisingvietnam.com/wp-content/uploads/2018/04/Du-l%E1%BB%8Bch-Vi%E1%BB%87t-Nam.jpg" alt="" />
    </div>
</div>

</div>

<script src="/assets/star_rating.js"></script>

homecoming/app/views/reviews/index.html.erb
<!------ Include the above in your HEAD tag ---------->
<main>
	<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<div class="container">
    <!-- Portfolio Item Row -->
    <div class="row">
        <div class="col-md-6">
            <img class="img-responsive" src="https://advertisingvietnam.com/wp-content/uploads/2018/04/Du-l%E1%BB%8Bch-Vi%E1%BB%87t-Nam.jpg" alt="">
        </div>
        <div class="col-md-6">
            <h3>Nha trang </h3>
            <p>Trong khi đi du lịch, Chúng ta sẽ tìm hiểu những địa điểm mới, quen biết thêm nhiều người hơn. Bằng cách tương tác với những địa điểm mới và những con người mới, chúng ta sẽ được tìm hiểu những di sản mà họ có. Trong trường hợp khác, nó giúp chúng ta có thể bồi dưỡng thêm về mặt tâm hồn và tính cách, tăng thêm kinh nghiệm sống. Hiểu thêm về bản chất con người có thể trở thành một phương pháp tốt trong việc giáo dục. Du lịch sẽ đáp ứng tất cả nhu cầu của một con người về, nó là một sở thích tốt giúp giải tỏa miền đam mê, bồi sưỡng tâm hồn và cả thể lực.</p>
            <ul>
                <li>Create by <a href="http://startbootstrap.com/template-overviews/portfolio-item">Homecomming</a>.</li>             
                <li>Rating by  <a href="http://tympanus.net/codrops/author/hugogiraudel">10</a> people <a href="http://tympanus.net/codrops/2012/11/14/creative-css-loading-animations/"></a>.</li>
                <li>
    <div class="col-lg-12">
      <div class="star-rating">
        <span class="fa fa-star-o" data-rating="1"></span>
        <span class="fa fa-star-o" data-rating="2"></span>
        <span class="fa fa-star-o" data-rating="3"></span>
        <span class="fa fa-star-o" data-rating="4"></span>
        <span class="fa fa-star-o" data-rating="5"></span>
        <input type="hidden" name="whatever1" class="rating-value" value="2.56">
      </div>
    </div>
                </li>
            </ul>
        </div>
    </div>
    <!-- Related Projects Row -->
    <h3 class="page-header">Comment</h3>
    <div class="row">
    	<br>
    	    <form action="mailto:someaddr@somedomainforexample.com" method="get">
   <textarea name="body" style="border-style: solid;"></textarea><br/>
    <input type="submit" value="submit">
    </form>
    </div>
    <hr>
    <div class="row">
        <div class="col-sm-3 col-xs-6">
            <a href="#"><img class="img-responsive portfolio-item" src="https://advertisingvietnam.com/wp-content/uploads/2018/04/Du-l%E1%BB%8Bch-Vi%E1%BB%87t-Nam.jpg" alt=""></a>
        </div>
        <div class="col-sm-3 col-xs-6">
            <a href="#"><img class="img-responsive portfolio-item" src="https://advertisingvietnam.com/wp-content/uploads/2018/04/Du-l%E1%BB%8Bch-Vi%E1%BB%87t-Nam.jpg" alt=""></a>
        </div>
        <div class="col-sm-3 col-xs-6">
            <a href="#"><img class="img-responsive portfolio-item" src="https://advertisingvietnam.com/wp-content/uploads/2018/04/Du-l%E1%BB%8Bch-Vi%E1%BB%87t-Nam.jpg" alt=""></a>
        </div>
        <div class="col-sm-3 col-xs-6">
            <a href="#"><img class="img-responsive portfolio-item" src="https://advertisingvietnam.com/wp-content/uploads/2018/04/Du-l%E1%BB%8Bch-Vi%E1%BB%87t-Nam.jpg" alt=""></a>
        </div>
    </div>
    <!-- /.row -->
    <hr>
</div>
<style type="text/css">
	li{
		display: list-item;
	}
</style>
<script type="text/javascript">
var $star_rating = $('.star-rating .fa');

var SetRatingStar = function() {
  return $star_rating.each(function() {
    if (parseInt($star_rating.siblings('input.rating-value').val()) >= parseInt($(this).data('rating'))) {
      return $(this).removeClass('fa-star-o').addClass('fa-star');
    } else {
      return $(this).removeClass('fa-star').addClass('fa-star-o');
    }
  });
};

$star_rating.on('click', function() {
  $star_rating.siblings('input.rating-value').val($(this).data('rating'));
  return SetRatingStar();
});

SetRatingStar();
$(document).ready(function() {

});
</script>
</main>

homecoming/app/views/reviews/new.html.erb
<div class="container">
<% if @review.errors.any? %>
    <div class="alert alert-danger" role="alert">
        <%= @review.errors.full_messages.first %>
    </div>
<% end %>
<hr>
<h2>Create new review for destination: 
    <span class="badge badge-secondary">
        <%= @review.destination.name %>
    </span>
</h2>

<%= form_for [@destination, @review] do |f| %>
  <div>
    <%= f.label :title %>
  </div>
  <div>
    <%= f.text_field :title, :class => 'col-12' %>
  </div>
  <hr>
  <div>
  <%= f.label :rating %>
</div>
  <div class="star-rating" display="inline">
    <span class="fa fa-star-o" data-rating="1"></span>
    <span class="fa fa-star-o" data-rating="2"></span>
    <span class="fa fa-star-o" data-rating="3"></span>
    <span class="fa fa-star-o" data-rating="4"></span>
    <span class="fa fa-star-o" data-rating="5"></span>
    <%= f.text_field :rating, :type => "hidden", :class => "rating-value" %>
    <strong class = "type">address</strong>
</div> 
  <hr>
  <div>
    <%= f.label :content %>
  </div>
  <div>
    <%= f.cktext_area :content, rows: 10 %>
  </div>
  <div>
    <%= f.hidden_field 'user_id', :value => @review.user.id %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

<hr>
<div class="item ">
    <div class="thumbnail">
        <div class="caption">
            <h4 class="group inner list-group-item-heading">
                <span class="badge badge-secondary">Destination: </span>
                <%= @review.destination.name %></h4>
        <p class="group inner list-group-item-text">
            <span class="badge badge-secondary">Address: </span>
            <%= @review.destination.address %></h4></p>
        <p class="group inner list-group-item-text">
            <span class="badge badge-secondary">Speciality: </span>
            <%= @review.destination.speciality %></h4></p>
            <img class="group list-group-image" src="https://advertisingvietnam.com/wp-content/uploads/2018/04/Du-l%E1%BB%8Bch-Vi%E1%BB%87t-Nam.jpg" alt="" />
    </div>
</div>

</div>

<script src="/assets/star_rating.js"></script>

homecoming/app/views/reviews/show.html.erb
<!-- Main content area -->
<main class="container">
    <div class="row">
        <!-- Sidebar -->
        <aside class="col-md-4">
            <div class="sidebar-box">
                <h4>More than Review</h4>
                <div class="list-group list-group-root">
                    <a class="list-group-item" href="index.html">Home Page</a>
                    <a class="list-group-item" href="examples.html">Place</a>
                    <div class="list-group">
                        <a class="list-group-item" href="three-column.html">new Place </a>
                        <a class="list-group-item" href="one-column.html">Place hot</a>
                        <a class="list-group-item active" href="text.html">Place suitable</a>
                    </div>
                    <a class="list-group-item" href="three-column.html">Place suggestions</a>
                </div>
            </div>
            <div class="sidebar-box sidebar-box-bg">
                <h4>About us</h4>
                <p>Aenean nec massa a tortor auctor sodales sed a dolor. Duis vitae lorem sem. Proin at velit vel arcu
                    pretium luctus. <a href="#" class="readmore">Read More &raquo;</a></p>
            </div>
            <div class="sidebar-box">
                <h4>Search site</h4>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                    <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
            <div class="sidebar-box">
                <h4>Helpful Links</h4>
                <ul>
                    <li><a href="http://www.themeforest.net/?ref=spykawg" title="premium templates">Premium HTML web
                            templates from $10</a></li>
                    <li><a href="http://www.dreamhost.com/r.cgi?259541" title="web hosting">Cheap web hosting from
                            Dreamhost</a></li>
                    <li><a href="http://tuxthemes.com" title="Tux Themes">Premium WordPress themes</a></li>
                </ul>
            </div>
        </aside>
        <!-- Main content -->
        <div class="col-md-8">
            <div>
                <div id="products" class="row list-group">
                    <div class="item ">
                        <div class="well" style="background-color:#ffffff">
                            <div class="media" style="height: 170px">
                                <div class="pull-left">
                                    <img class="media-object" src="http://placekitten.com/150/150" alt="">
                                    <p style="width: 150px;text-align:center">
                                    </p>
                                </div>
                                <div class="media-body">
                                    <h3 class="media-heading">
                                        <%= @review.title %>
                                        <%# <%= link_to review.title, controller: "reviews", action: "show", id: review.id %>
                                    </h3>
                                    <% if current_user.id == @review.user.id %>
                                    <div class="pull-right ml-3">
                                        <%= link_to 'Delete', destination_review_path(@review), method: :delete %>
                                    </div>
                                    <div class="pull-right">
                                        <%= link_to 'Edit', edit_destination_review_path(@review) %>
                                    </div>
                                    <% end %>
                                    <div style="height:60px;line-height:20px; /* Height / no. of lines to display */overflow:hidden; margin-bottom:30px">
                                        <%= @review.content.html_safe %>
                                    </div>
                                    <ul class="list-inline list-unstyled text-right">
                                        <li><span><i class="glyphicon glyphicon-calendar"></i>
                                                <%= @review.created_at%> </span></li>
                                        <li>|</li>
                                        <span><i class="glyphicon glyphicon-comment"></i>
                                            <%= @review.comments.count%></span>
                                        <li>|</li>
                                        <li>
                                            <%= render 'shared/star', :locals => {:rating => @review.rating  }%>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="item ">
                        <div class="thumbnail">
                            <img class="group list-group-image" src="https://advertisingvietnam.com/wp-content/uploads/2018/04/Du-l%E1%BB%8Bch-Vi%E1%BB%87t-Nam.jpg"
                                alt="" />
                            <div class="caption">
                                <h4 class="group inner list-group-item-heading">
                                    <span class="badge badge-secondary">Destination: </span>
                                    <%= @review.destination.name %>
                                </h4>
                                <p class="group inner list-group-item-text">
                                    <span class="badge badge-secondary">Address: </span>
                                    <%= @review.destination.address %>
                                    </h4>
                                </p>
                                <p class="group inner list-group-item-text">
                                    <span class="badge badge-secondary">Speciality: </span>
                                    <%= @review.destination.speciality %>
                                    </h4>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div id="replies-for-">
                <%= render "comments/comment_form", review: @review, parent_id: nil, comment_new: @comment %>
                <br>
                <br>
                <%= comments_tree_for @review.comments.hash_tree(limit_depth: 5), @review %>
            </div>
        </div>
    </div>
    <!-- Bootcamp JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
</main>