homecoming/config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  mount Ckeditor::Engine => '/ckeditor'
  root 'static_pages#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'static_pages/home'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'profile', to: 'user#show'

  resources :destinations do
    resources :reviews do
      resources :comments, only: [:create, :destroy, :update]
    end
  end
  resources :users
  resources :groups, only: [:new, :create, :show, :destroy] do
    resources :news
  end
  get '/search' => 'destinations#search', :as => 'search_page'
  get '/create_group' => 'tests#create_group'
  get '/show_group' => 'tests#show_group'
  get '/destroy_group' => 'tests#destroy_group'
  get '/add_member_to_group' => 'tests#add_member_to_group'

  mount ActionCable.server => '/cable'
end

homecoming/app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :review
    has_many :children, class_name: 'Comment', foreign_key: 'parent_id', dependent: :destroy, inverse_of: 'parent'
    belongs_to :parent, class_name: 'Comment', optional: true

    validates :content, presence: true
    validates :user, presence: true
    validates :review, presence: true

    acts_as_tree order: "created_at ASC"

    after_create_commit { notify }

    private
    def notify
        review = Review.find_by(id: self.review_id)
        destination = Destination.find_by(id: review.destination_id)
        Notification.create(event: "New comment review on post (#{destination.name})", comment_id: self.id, review_id: self.review_id, destination_id: review.destination_id)
    end
end

homecoming/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_comment, only: [:destroy]
    def create
        if params[:comment][:parent_id].to_i > 0
            parent = Comment.find_by id: params[:comment].delete(:parent_id)
            @comment = parent.children.build comment_params
            else
                @comment = Comment.new comment_params
            end
            if @comment.save
            respond_to do |format|
                # format.html{redirect_back(fallback_location: root_path)}
                format.js
            end
        end
    end

    def update
        @comment = Comment.find(params[:id])
        if @comment.update!(comment_params)
            respond_to do |format|
                format.js
            end
        end
    end

    def destroy
        # @comment.descendants.each do |comment_des|
        #   comment_des.destroy
        # end
        @comment = Comment.find(params[:id])
        @comment.destroy
        # @review = Review.find(params[:review_id])
        # redirect_to [@review.destination, @review]
        respond_to do |format|
            format.js
        end
    end

    private

    def set_comment
        @comment = Comment.find_by id: params[:id]
    end

    def comment_params
        params.require(
          :comment
        ).permit(
          :parent_id,
          :review_id,
          :content,
          :user_id
        )
    end
end

homecoming/app/helpers/comments_helper.rb
module CommentsHelper
  def comments_tree_for comments, post
      safe_join(comments.map do |comment, nested_comments|
                  print(comment)
                  print(nested_comments)
                  render(comment, review: post, comment_new: Comment.new) + tree(comment, nested_comments, post)
                end
      )
  end
  def tree comment, nested_comments, post
    if nested_comments.empty?
      render :partial => 'comments/replies_for', :locals => {:comment_id => comment.id }
    else
      content_tag :div, comments_tree_for(nested_comments, post), class: "replies", id: ("replies-for-" + comment.id.to_s)
    end
  end
end

homecoming/app/views/comments/_comment.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1"
 crossorigin="anonymous">
<link rel="stylesheet" href="/assets/comments.css">
<!------ Include the above in your HEAD tag ---------->
<!-- Respuestas de los comentarios -->
<div class="row comment" id="comment-container-<%= comment.id %>">
	<div id="form-comment<%= review.id %>" style="width: 95%">
		<div>
			<div class="comment-main-level" style="width: 95%">
				<!-- Avatar -->
				<% if comment.user.picture_path != nil %>
				<div class="comment-avatar"><img style="max-height: 60px" src="<%= comment.user.picture_path%>" alt="no picture"></div>
				<% else %>
				<div class="comment-avatar"><img style="max-height: 60px" src="http://digitalspyuk.cdnds.net/17/25/980x490/landscape-1498216547-avatar-neytiri.jpg"
					 alt="no picture"></div>
				<% end %>
				<!-- Contenedor del Comentario -->
				<div class="comment-box">
					<div class="comment-head">
					<%if comment.user.id == comment.review.user.id%>
						<h6 class="comment-name by-author">
						<% else %>
						<h6 class="comment-name">
						<%end%>

							<%= link_to comment.user.nickname, user_path(comment.user_id) %>
						</h6>
						<span>
							<%= comment.created_at %></span>
						<i class="fa fa-reply" id="<%=comment.id%>" onclick="Reply(this)"></i>
						<% if current_user.id == comment.user.id %>
						<i class="fa fa-remove">
							<%= link_to "Delete", destination_review_comment_path(comment.review.destination, comment.review, comment), remote: true, method: :delete %></i>
						<i class="fa fa-edit" onclick="open_edit_comment(this);" data-comment-id="<%= comment.id %>">Edit</i>
						<%end%>
					</div>
					<div class="comment-content">
						<div id="comment-content-<%= comment.id %>">
						<%= comment.content %>
						</div>
						<div id="comment-edit-container-<%= comment.id %>" style="display: none;">
							<hr>
							<%= form_for comment, url: destination_review_comment_url(comment.review.destination, comment.review, comment), remote: true do |f| %>
								<%= f.hidden_field :id, value: comment.id %>
								<%= f.text_area :content, placeholder: "Enter update comemnt", :style => "display: inline-block;",
								  required: true, class: "form-control comment-input" %>
								  <br><br>
								  <div>
								<%= f.submit "Submit", class: "btn btn-xs btn-custom2", style: "float: right;" %>
								</div>
								
							<% end %>
							
						</div>
					</div>
					
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-1" id="What The Fuck"></div>
	<div class="row reply_part" id='reply_<%=comment.id%>' style="display: none; width: 90%">
		<div class="comment-main-level reply-box" style="width: 95%">
			<!-- Avatar -->
			<% if comment.user.picture_path == nil %>
			<div class="comment-avatar"><img style="max-height: 60px" src="<%= comment.user.picture_path%>" alt="no picture"></div>
			<% else %>
			<div class="comment-avatar"><img style="max-height: 60px" src="http://digitalspyuk.cdnds.net/17/25/980x490/landscape-1498216547-avatar-neytiri.jpg"
				 alt="no picture"></div>
			<% end %>
			<!-- Contenedor del Comentario -->
			<div class="comment-box" style="width: 85%">
				<div class="col-md-13 comment-content" style="width: 100%">
					<%= render "comments/comment_form", review: review, parent_id: comment.id,
				comment_new: comment_new %>
				</div>
			</div>
		</div>
	</div>
</div>
<script src="/assets/reply.js"></script>

homecoming/app/views/comments/_comment_form.html.erb
<% if user_signed_in? %>
  <span id="form-comment" style= "width: 95%">
    <%= form_for [review.destination, review, comment_new], remote: true do |f| %>
      <%= f.hidden_field :parent_id, value: parent_id %>
      <%= f.hidden_field :review_id, value: review.id %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.text_area :content, placeholder: "Commpose new comment", :style => "display: inline-block;",
        required: true, class: "form-control comment-input" %>
        <br><br>
        <div>
      <%= f.submit "Submit", class: "btn btn-xs btn-custom2", style: "float: right;" %>
      </div>
      
    <% end %>
  </span>
<% end %>

homecoming/app/views/comments/_replies_for.html.erb
<div class="replies" id="replies-for-<%= comment_id %>">
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
<link rel="stylesheet" href="/assets/comments.css">
<script src="/assets/reply.js"></script>
</div>

homecoming/app/views/comments/create.js.erb
console.log('Begin add new comment: <%= @comment.id %>');
$('.comment-input').val('');
console.log($('#replies-for-<%= @comment.parent_id %>'));
$('#replies-for-<%= @comment.parent_id %>').append('<%= escape_javascript(render(@comment, review: @comment.review, comment_new: Comment.new)) %>');
$('#replies-for-<%= @comment.parent_id %>').append('<%= escape_javascript(render :partial => 'comments/replies_for', :locals => {:comment_id => @comment.id }) %>');
$('html, body').animate({
	scrollTop: $("#comment-container-<%= @comment.id %>").offset().top
},1000);

homecoming/app/views/comments/destroy.js.erb
console.log("Begin delete: " + <%= @comment.id %>);
$('#comment-container-<%= @comment.id %>').remove();
console.log("End delete: " + <%= @comment.id %>);
$('#replies-for-<%= @comment.id %>').remove();

homecoming/app/views/comments/update.js.erb
console.log("Started update.js");
console.log('#comment-content-<%= @comment.parent_id %>');
$('#comment-content-<%= @comment.id %>').html('<%= @comment.content %>')
$('#comment-edit-container-<%= @comment.id %>').css("display", "none");